### ISSUE TITLE
App Prototyping

### ISSUE THREAD

**Issue by heatherbooker** [heatherbooker/french-countries-and-nationalities#1]
- used Marvel App to prototype various screens

https://marvelapp.com/14cac5b

**\- 3 question types:** 
- English: type French translation
- French: type English translation
- English: choose correct French translation

**\- 2 categories:**
- countries
- nationalities

**\- areas:**
- North America
- South America
- Europe
- Africa
- Asia
- Oceania

**Comment by heatherbooker** [comment]
@dharness can i get a review? https://marvelapp.com/14cac5b

**Comment by heatherbooker** [comment]
update: switched to inkscape to make my own mockups, will be keeping in a folder 'prototype'

**Comment by dharness** [comment]
Can you edit the initial comment to include a link?

**Comment by heatherbooker** [comment]
**updated** marvel app prototype with screens created in inkscape:

https://marvelapp.com/1b75d56

edit: some changes made - @dharness let me know what you think

**Comment by heatherbooker** [comment]
initial prototyping complete
