### ISSUE TITLE
using links <a href=""> in jsx

### ISSUE THREAD

**Issue by heatherbooker** [heatherbooker/french-countries-and-nationalities#12]
currently in index.jsx I have declared a destination:
`var home = 'index.html';`

but if I try to reference it later on (line 27):
`<h1 className='nav-logo'><a href=home>Frenchly</a></h1>`

it throws an error.

**TO DO:** look into this.

**Comment by dharness** [comment]
@heatherbooker pretty sure it should be `<a href={home}>` as per:
https://facebook.github.io/react/docs/jsx-in-depth.html

**Comment by heatherbooker** [comment]
rad thanks @dharness
