### ISSUE TITLE
Problems with Google Drive command line client

### ISSUE THREAD

**Issue by heatherbooker** [heatherbooker/french-countries-and-nationalities#7]
the first step is setting up the Go programming language, which is proving difficult, perhaps due to my lack of understanding of environment variables.  
using this website https://golang.org/doc/install?download=go1.6.2.linux-amd64.tar.gz

next step for google drive client is found at https://github.com/odeke-em/drive

this  
`go install github.com/user/hello`  
currently elicits this  
`command not found: go`  

will re-investigate tomorrow

**Comment by dharness** [comment]
I didn't realize this require you to run a command-line tool. You don't have to use this if you don't want to

**Comment by heatherbooker** [comment]
switched to dropbox for file sharing
